[package]
name = "expr-vergen"
version = "0.1.0"
authors = ["Wink Saville <wink@saville.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
vergen = "5.1.8"
